### ISSUE TITLE
Define websocket API

### ISSUE THREAD

**Issue by jtsymon** [Arcton/DataDecks#6]

**Comment by jtsymon** [comment]
> That moment when I don't realise I can't assign multiple people to an issue

**Comment by nathanielw** [comment]
So this is something for us both to do I take it?

**Comment by jtsymon** [comment]
Yeah, by API I meant the communication between the server and the client.
I'm thinking we could go for JSON strings, since both server and client are using javascript?

**Comment by nathanielw** [comment]
Definitely. :heart: me some JSON.
